# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "assets", :force => true do |t|
    t.column "name",         :string
    t.column "content_type", :string
    t.column "body",         :binary
  end

  create_table "users", :force => true do |t|
    t.column "name",                      :string
    t.column "email",                     :string
    t.column "able_license",              :string
    t.column "company",                   :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "password_reset_code",       :string,   :limit => 40
  end

end
